dist: bionic
os: linux

language: rust
cache: cargo

matrix: 
	fast_finish: true

	include:
		- name: "Stable"
		  rust: stable
	          script: 
			- cargo build --verbose --all
			- cargo test --verbose --all

